# TODO: use newest golang alpine image to build the binary
# TODO: copy the binary into a scratch image (see https://docs.docker.com/develop/develop-images/multistage-build/)
# TODO: set the ENTRYPOINT to execute the app
