#!/bin/sh -eu

watchAndBuild() {
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    while true; do
        find . -iname 'docker-compose.yml' |
        while read -r line; do
        (
            cd "$(dirname "$line")";
            set -x;
            TAG="$(git rev-parse HEAD)"
            export APP_VERSION="$TAG"
            docker-compose build;
            docker-compose push;
            cd ../deployment/base/;
            kustomize edit set image '*'=:"$TAG";
            kustomize build | kubectl apply -f -;
        );
        done;
        echo "Polling for changes to $(git remote get-url origin)...";
        while true; do
            2>&1 git fetch -v --progress origin;
            if [ "$(2>&1 git rev-parse HEAD)" != "$(2>&1 git rev-parse origin/"$BRANCH")" ]; then
                break;
            fi;
            echo .;
            sleep 1;
        done | stdin-spinner;
        git reset --hard origin/"$BRANCH";
    done
}

watchAndBuild;
